apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tp-grupo1
  namespace: grupo1
  labels:
    app: tp-grupo1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-grupo1
  template:
    metadata:
      labels:
        app: tp-grupo1
    spec:
      containers:
        - name: apache
          image: ulisesaguirre/tp-grupo1:v1
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
